### ISSUE TITLE
Puntualizaciones y preguntas sobre varios puntos de la guía

### ISSUE THREAD

**Issue by JesusBusquets** [sincrum/genexus#1]
Incluiré aquí algunos comentarios sobre varios puntos de la guía.

1.7: El nombrar las transacciones con el nombre en plural es lo que parece natural a la hora de que Genexus cree la tabla con ese nombre. Pero, si no me equivoco, no es la suposición que hace Genexus, sino que por diseño se considera que las transacciones llevan el nombre de la entidad en singular. Así, los mensajes de error, cuando falla, por ejemplo, la integridad relacional, lo convierte bien al plural, No se si en las últimas versiones de genexus este comportamiento ha cambiado. 

3.1:  Esta norma ¿no generaría un número elevado de dominios enumerados? ¿en la práctica es manejable el resultado?

6.1: Esta forma de hacer comentarios multilínea, con /**   */   hace que haya que editar manualmente cada una de las líneas de código para añadir un asterisco, ¿no es así? Puesto que Genexus tiene una tecla rápida para comentar un grupo de líneas, ¿no haría que se perdiera mucha productividad teniendo que editar cada línea de código cuando se quiera comentar una zona de código?  ¿O existe una forma de comentar con este estilo de forma rápida?

8.1 : Esta es la parte que me ofrece mas dudas. Comenté algo parecido respecto al punto 3.1, pero pienso que aquí es mas exagerado aún: ¿no crearíamos un gran número de SDT para todos los conjuntos de parámetros de llamada entre programas? Además, estos SDT ¿no serían en una gran parte una serie de datos "ad-hoc", que tienen sentido sólo en el contexto de la llamada a un procedimiento concreto, y no una significación conceptual propia?  

Además, entiendo que esto se aplicaría a parámetros de un solo tipo respecto a E/S, es decir, sí que habría que separar los parámetros de entrada de los de salida.

**Comment by sincrum** [comment]
1.7 Esto también es una buena práctica al utilizar patterns.

3.1 Es bien manejable y práctico. Por ejemplo al crear parámetros, es más sencillo utilizar un dominio enumerado que acordarse del texto.

6.1 Igual esto tiene sentido para encabezados o comentarios de funcionamiento extensos a medida que se escriben. Igual es un tema subjetivo.

8.1 En este caso, hay que evaluar ya que no es una regla para todos los procs. Se debe evaluar de-acuerdo a la cantidad de parámetros "In" del proc y su posibilidad de agregados en un futuro. Diría que si tiene 4 o más parámetros, utilizar un SDT. En el caso de webservices si es más necesario.
Se hace una diferencia con parámetros In y Out ya que debieran ir en estructuras y variables por separado.
