### ISSUE TITLE
parametros en objetos

### ISSUE THREAD

**Issue by ramunozp** [sincrum/genexus#4]
original::
// mal
parm(in:PaiId,out:&PaiNom);

// bien
parm( in:PaiId, out:&PaiNom);

Propuesta:
si bien eso es lo típico que se ve y se propagó en GX, para mi no es lo mejor ni lo mas legible, sobre todo cuando la cantidad de parámetros es grande. yo propongo y uso lo siguiente:

// MEJOR
parm( 
        in: PaiId, 
        out: &PaiNom
        );

donde los Tab's son los que da por defecto GX y primero se deben dejar todos los IN y al final los OUT, como debería ser. De esta forma, si un procedimiento tiene parámetros es muy fácil ver como es y sobre todo si la lista de parámetros es extensa.

**Comment by gxsoft** [comment]
De Acuerdo con Mejor

--
Saludos,
gab
@gxsoft

**Comment by dmonza** [comment]
@ramunozp está interesante la propuesta. Capaz se puede agregar como opcional en el caso que existan demasiados parámetros. Aunque en este último caso es preferible un SDT.

**Comment by ramunozp** [comment]
Si claro, si son muchos parametros, siempre es mejor un SDT, aun que me ha tocado tener SDT muy grandes que no son soportados o no funcionan muy bien por parametros y he tenido que pasarlos por websession.

De todas maneras lo que indico no es para competir con un sdt por parametros, si no mas bien, como quedan mejor escritos los parametros y, a mi juicio, como debería ser.  

Se ve mejor en GX que aquí, como texto.

![Captura de Pantalla 2022-02-18 a la(s) 16 13 01](https://user-images.githubusercontent.com/24207310/154747232-48f08c44-add6-4585-88b7-9ff3dd026127.png)
